(function(i){var e=function(o,l){var t=i.extend({},i.fn.nivoSlider.defaults,l);var e={currentSlide:0,currentImage:'',totalSlides:0,running:!1,paused:!1,stop:!1,controlNavEl:!1};var n=i(o);n.data('nivo:vars',e).addClass('nivoSlider');var a=n.children();a.each(function(){var t=i(this),n='';if(!t.is('img')){if(t.is('a')){t.addClass('nivo-imageLink');n=t};t=t.find('img:first')};var a=a===0?t.attr('width'):t.width(),o=o===0?t.attr('height'):t.height();if(n!==''){n.css('display','none')};t.css('display','none');e.totalSlides++});if(t.randomStart){t.startSlide=Math.floor(Math.random()*e.totalSlides)};if(t.startSlide>0){if(t.startSlide>=e.totalSlides){t.startSlide=e.totalSlides-1};e.currentSlide=t.startSlide};if(i(a[e.currentSlide]).is('img')){e.currentImage=i(a[e.currentSlide])}
else{e.currentImage=i(a[e.currentSlide]).find('img:first')};if(i(a[e.currentSlide]).is('a')){i(a[e.currentSlide]).css('display','block')};var s=i('<img/>').addClass('nivo-main-image');s.attr('src',e.currentImage.attr('src')).show();n.append(s);i(window).resize(function(){n.children('img').width(n.width());s.attr('src',e.currentImage.attr('src'));s.stop().height('auto');i('.nivo-slice').remove();i('.nivo-box').remove()});n.append(i('<div class="nivo-caption"></div>'));var h=function(t){var o=i('.nivo-caption',n);if(e.currentImage.attr('title')!=''&&e.currentImage.attr('title')!=undefined){var a=e.currentImage.attr('title');if(a.substr(0,1)=='#')a=i(a).html();if(o.css('display')=='block'){setTimeout(function(){o.html(a)},t.animSpeed)}
else{o.html(a);o.stop().fadeIn(t.animSpeed)}}
else{o.stop().fadeOut(t.animSpeed)}};h(t);var r=0;if(!t.manualAdvance&&a.length>1){r=setInterval(function(){d(n,a,t,!1)},t.pauseTime)};if(t.directionNav){n.append('<div class="nivo-directionNav"><a class="nivo-prevNav">'+t.prevText+'</a><a class="nivo-nextNav">'+t.nextText+'</a></div>');i(n).on('click','a.nivo-prevNav',function(){if(e.running){return!1};clearInterval(r);r='';e.currentSlide-=2;d(n,a,t,'prev')});i(n).on('click','a.nivo-nextNav',function(){if(e.running){return!1};clearInterval(r);r='';d(n,a,t,'next')})};if(t.controlNav){e.controlNavEl=i('<div class="nivo-controlNav"></div>');n.after(e.controlNavEl);for(var f=0;f<a.length;f++){if(t.controlNavThumbs){e.controlNavEl.addClass('nivo-thumbs-enabled');var v=a.eq(f);if(!v.is('img')){v=v.find('img:first')};if(v.attr('data-thumb'))e.controlNavEl.append('<a class="nivo-control" rel="'+f+'"><img src="'+v.attr('data-thumb')+'" alt="" /></a>')}
else{e.controlNavEl.append('<a class="nivo-control" rel="'+f+'">'+(f+1)+'</a>')}};i('a:eq('+e.currentSlide+')',e.controlNavEl).addClass('active');i('a',e.controlNavEl).bind('click',function(){if(e.running)return!1;if(i(this).hasClass('active'))return!1;clearInterval(r);r='';s.attr('src',e.currentImage.attr('src'));e.currentSlide=i(this).attr('rel')-1;d(n,a,t,'control')})};if(t.pauseOnHover){n.hover(function(){e.paused=!0;clearInterval(r);r=''},function(){e.paused=!1;if(r===''&&!t.manualAdvance){r=setInterval(function(){d(n,a,t,!1)},t.pauseTime)}})};n.bind('nivo:animFinished',function(){s.attr('src',e.currentImage.attr('src'));e.running=!1;i(a).each(function(){if(i(this).is('a')){i(this).css('display','none')}});if(i(a[e.currentSlide]).is('a')){i(a[e.currentSlide]).css('display','block')};if(r===''&&!e.paused&&!t.manualAdvance){r=setInterval(function(){d(n,a,t,!1)},t.pauseTime)};t.afterChange.call(this)});var c=function(e,o,t){if(i(t.currentImage).parent().is('a'))i(t.currentImage).parent().css('display','block');i('img[src="'+t.currentImage.attr('src')+'"]',e).not('.nivo-main-image,.nivo-control img').width(e.width()).css('visibility','hidden').show();var r=i('img[src="'+t.currentImage.attr('src')+'"]',e).not('.nivo-main-image,.nivo-control img').parent().is('a')?i('img[src="'+t.currentImage.attr('src')+'"]',e).not('.nivo-main-image,.nivo-control img').parent().height():i('img[src="'+t.currentImage.attr('src')+'"]',e).not('.nivo-main-image,.nivo-control img').height();for(var a=0;a<o.slices;a++){var n=Math.round(e.width()/o.slices);if(a===o.slices-1){e.append(i('<div class="nivo-slice" name="'+a+'"><img src="'+t.currentImage.attr('src')+'" style="position:absolute; width:'+e.width()+'px; height:auto; display:block !important; top:0; left:-'+(n+a*n-n)+'px;" /></div>').css({left:n*a+'px',width:e.width()-n*a+'px',height:r+'px',opacity:'0',overflow:'hidden'}))}
else{e.append(i('<div class="nivo-slice" name="'+a+'"><img src="'+t.currentImage.attr('src')+'" style="position:absolute; width:'+e.width()+'px; height:auto; display:block !important; top:0; left:-'+(n+a*n-n)+'px;" /></div>').css({left:n*a+'px',width:n+'px',height:r+'px',opacity:'0',overflow:'hidden'}))}};i('.nivo-slice',e).height(r);s.stop().animate({height:i(t.currentImage).height()},o.animSpeed)},m=function(e,n,a){if(i(a.currentImage).parent().is('a'))i(a.currentImage).parent().css('display','block');i('img[src="'+a.currentImage.attr('src')+'"]',e).not('.nivo-main-image,.nivo-control img').width(e.width()).css('visibility','hidden').show();var r=Math.round(e.width()/n.boxCols),c=Math.round(i('img[src="'+a.currentImage.attr('src')+'"]',e).not('.nivo-main-image,.nivo-control img').height()/n.boxRows);for(var o=0;o<n.boxRows;o++){for(var t=0;t<n.boxCols;t++){if(t===n.boxCols-1){e.append(i('<div class="nivo-box" name="'+t+'" rel="'+o+'"><img src="'+a.currentImage.attr('src')+'" style="position:absolute; width:'+e.width()+'px; height:auto; display:block; top:-'+c*o+'px; left:-'+r*t+'px;" /></div>').css({opacity:0,left:r*t+'px',top:c*o+'px',width:e.width()-r*t+'px'}));i('.nivo-box[name="'+t+'"]',e).height(i('.nivo-box[name="'+t+'"] img',e).height()+'px')}
else{e.append(i('<div class="nivo-box" name="'+t+'" rel="'+o+'"><img src="'+a.currentImage.attr('src')+'" style="position:absolute; width:'+e.width()+'px; height:auto; display:block; top:-'+c*o+'px; left:-'+r*t+'px;" /></div>').css({opacity:0,left:r*t+'px',top:c*o+'px',width:r+'px'}));i('.nivo-box[name="'+t+'"]',e).height(i('.nivo-box[name="'+t+'"] img',e).height()+'px')}}};s.stop().animate({height:i(a.currentImage).height()},n.animSpeed)},d=function(t,f,e,u){var n=t.data('nivo:vars');if(n&&n.currentSlide===n.totalSlides-1){e.lastSlide.call(this)};if((!n||n.stop)&&!u){return!1};e.beforeChange.call(this);if(!u){s.attr('src',n.currentImage.attr('src'))}
else{if(u==='prev'){s.attr('src',n.currentImage.attr('src'))};if(u==='next'){s.attr('src',n.currentImage.attr('src'))}};n.currentSlide++;if(n.currentSlide===n.totalSlides){n.currentSlide=0;e.slideshowEnd.call(this)};if(n.currentSlide<0){n.currentSlide=n.totalSlides-1};if(i(f[n.currentSlide]).is('img')){n.currentImage=i(f[n.currentSlide])}
else{n.currentImage=i(f[n.currentSlide]).find('img:first')};if(e.controlNav){i('a',n.controlNavEl).removeClass('active');i('a:eq('+n.currentSlide+')',n.controlNavEl).addClass('active')};h(e);i('.nivo-slice',t).remove();i('.nivo-box',t).remove();var a=e.effect,v='';if(e.effect==='random'){v=new Array('sliceDownRight','sliceDownLeft','sliceUpRight','sliceUpLeft','sliceUpDown','sliceUpDownLeft','fold','fade','boxRandom','boxRain','boxRainReverse','boxRainGrow','boxRainGrowReverse');a=v[Math.floor(Math.random()*(v.length+1))];if(a===undefined){a='fade'}};if(e.effect.indexOf(',')!==-1){v=e.effect.split(',');a=v[Math.floor(Math.random()*v.length)];if(a===undefined){a='fade'}};if(n.currentImage.attr('data-transition')){a=n.currentImage.attr('data-transition')};n.running=!0;var o=0,r=0,d='',l='',I='',g='';if(a==='sliceDown'||a==='sliceDownRight'||a==='sliceDownLeft'){c(t,e,n);o=0;r=0;d=i('.nivo-slice',t);if(a==='sliceDownLeft'){d=i('.nivo-slice',t)._reverse()};d.each(function(){var n=i(this);n.css({top:'0px'});if(r===e.slices-1){setTimeout(function(){n.animate({opacity:'1.0'},e.animSpeed,'',function(){t.trigger('nivo:animFinished')})},100+o)}
else{setTimeout(function(){n.animate({opacity:'1.0'},e.animSpeed)},100+o)};o+=50;r++})}
else if(a==='sliceUp'||a==='sliceUpRight'||a==='sliceUpLeft'){c(t,e,n);o=0;r=0;d=i('.nivo-slice',t);if(a==='sliceUpLeft'){d=i('.nivo-slice',t)._reverse()};d.each(function(){var n=i(this);n.css({bottom:'0px'});if(r===e.slices-1){setTimeout(function(){n.animate({opacity:'1.0'},e.animSpeed,'',function(){t.trigger('nivo:animFinished')})},100+o)}
else{setTimeout(function(){n.animate({opacity:'1.0'},e.animSpeed)},100+o)};o+=50;r++})}
else if(a==='sliceUpDown'||a==='sliceUpDownRight'||a==='sliceUpDownLeft'){c(t,e,n);o=0;r=0;var N=0;d=i('.nivo-slice',t);if(a==='sliceUpDownLeft'){d=i('.nivo-slice',t)._reverse()};d.each(function(){var n=i(this);if(r===0){n.css('top','0px');r++}
else{n.css('bottom','0px');r=0};if(N===e.slices-1){setTimeout(function(){n.animate({opacity:'1.0'},e.animSpeed,'',function(){t.trigger('nivo:animFinished')})},100+o)}
else{setTimeout(function(){n.animate({opacity:'1.0'},e.animSpeed)},100+o)};o+=50;N++})}
else if(a==='fold'){c(t,e,n);o=0;r=0;i('.nivo-slice',t).each(function(){var n=i(this),a=n.width();n.css({top:'0px',width:'0px'});if(r===e.slices-1){setTimeout(function(){n.animate({width:a,opacity:'1.0'},e.animSpeed,'',function(){t.trigger('nivo:animFinished')})},100+o)}
else{setTimeout(function(){n.animate({width:a,opacity:'1.0'},e.animSpeed)},100+o)};o+=50;r++})}
else if(a==='fade'){c(t,e,n);l=i('.nivo-slice:first',t);l.css({width:t.width()+'px'});l.animate({opacity:'1.0'},e.animSpeed*2,'',function(){t.trigger('nivo:animFinished')})}
else if(a==='slideInRight'){c(t,e,n);l=i('.nivo-slice:first',t);l.css({width:'0px',opacity:'1'});l.animate({width:t.width()+'px'},e.animSpeed*2,'',function(){t.trigger('nivo:animFinished')})}
else if(a==='slideInLeft'){c(t,e,n);l=i('.nivo-slice:first',t);l.css({width:'0px',opacity:'1',left:'',right:'0px'});l.animate({width:t.width()+'px'},e.animSpeed*2,'',function(){l.css({left:'0px',right:''});t.trigger('nivo:animFinished')})}
else if(a==='boxRandom'){m(t,e,n);I=e.boxCols*e.boxRows;r=0;o=0;g=p(i('.nivo-box',t));g.each(function(){var n=i(this);if(r===I-1){setTimeout(function(){n.animate({opacity:'1'},e.animSpeed,'',function(){t.trigger('nivo:animFinished')})},100+o)}
else{setTimeout(function(){n.animate({opacity:'1'},e.animSpeed)},100+o)};o+=20;r++})}
else if(a==='boxRain'||a==='boxRainReverse'||a==='boxRainGrow'||a==='boxRainGrowReverse'){m(t,e,n);I=e.boxCols*e.boxRows;r=0;o=0;var w=0,S=0,b=[];b[w]=[];g=i('.nivo-box',t);if(a==='boxRainReverse'||a==='boxRainGrowReverse'){g=i('.nivo-box',t)._reverse()};g.each(function(){b[w][S]=i(this);S++;if(S===e.boxCols){w++;S=0;b[w]=[]}});for(var R=0;R<e.boxCols*2;R++){var x=R;for(var y=0;y<e.boxRows;y++){if(x>=0&&x<e.boxCols){(function(n,o,r,c,f){var s=i(b[n][o]),l=s.width(),d=s.height();if(a==='boxRainGrow'||a==='boxRainGrowReverse'){s.width(0).height(0)};if(c===f-1){setTimeout(function(){s.animate({opacity:'1',width:l,height:d},e.animSpeed/1.3,'',function(){t.trigger('nivo:animFinished')})},100+r)}
else{setTimeout(function(){s.animate({opacity:'1',width:l,height:d},e.animSpeed/1.3)},100+r)}})(y,x,o,r,I);r++};x--};o+=100}}},p=function(i){for(var t,n,e=i.length;e;t=parseInt(Math.random()*e,10),n=i[--e],i[e]=i[t],i[t]=n);return i},u=function(i){if(this.console&&typeof console.log!=='undefined'){console.log(i)}};this.stop=function(){if(!i(o).data('nivo:vars').stop){i(o).data('nivo:vars').stop=!0;u('Stop Slider')}};this.start=function(){if(i(o).data('nivo:vars').stop){i(o).data('nivo:vars').stop=!1;u('Start Slider')}};t.afterLoad.call(this);return this};i.fn.nivoSlider=function(t){return this.each(function(n,a){var o=i(this);if(o.data('nivoslider')){return o.data('nivoslider')};var r=new e(this,t);o.data('nivoslider',r)})};i.fn.nivoSlider.defaults={effect:'random',slices:15,boxCols:8,boxRows:4,animSpeed:500,pauseTime:3e3,startSlide:0,directionNav:!0,controlNav:!0,controlNavThumbs:!1,pauseOnHover:!0,manualAdvance:!1,prevText:'Prev',nextText:'Next',randomStart:!1,beforeChange:function(){},afterChange:function(){},slideshowEnd:function(){},lastSlide:function(){},afterLoad:function(){}};i.fn._reverse=[].reverse})(jQuery);