# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    




    # add more services, or override services that need manual wiring
    # AppBundle\Service\ExampleService:
    #     arguments:
    #         $someArgument: 'some_value'
    ns.form.registration:
        class: NS\UserBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: ns_user_registration }