<?php

namespace NS\ScenesBundle\Repository;

/**
 * SceneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProposedSceneRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLatestProposedScene($id, $nbre)
    {
        return $this->createQueryBuilder('p')
            ->where('p.isEnabled = :true')
            ->andWhere('p.scene = :id')
            ->orderBy('p.createdAt')
            ->setParameter('true', true)
            ->setParameter('id', $id)
            ->setMaxResults($nbre)
            ->getQuery()
            ->getResult();

    }

    public function LastProposed($id)
    {
        $count=  $this->createQueryBuilder('p')
            ->join('p.scene', 'sc')
            ->addSelect('sc')
            ->where('sc.isEnabled = :true')
            ->andWhere('sc.id = :scene')
            ->orderBy('p.id', 'DESC')
            ->setParameter('true', true)
            ->setParameter('scene', $id)
            ->setMaxResults(1)
            ->getQuery()
            ->getResult();

        //dump($count[0]); exit;

        if($count != null)
            return $count[0]->getCount() + 1;
        else
            return 1;

        return $count;

    }

    public function NumberOfProposedScenes()
    {
        $qb = $this->createQueryBuilder('u')
            ->select('count(u.id)');

        return $qb->getQuery()->getSingleScalarResult();
    }
}
