<?php

namespace NS\ScenesBundle\Repository;

/**
 * StorylineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StorylineRepository extends \Doctrine\ORM\EntityRepository
{
    public function NumberOfStorylines()
    {
        $qb = $this->createQueryBuilder('u')
            ->select('count(u.id)');

        return $qb->getQuery()->getSingleScalarResult();
    }

    public function getStoryChart()
    {
        $sql = "SELECT count(id) as nbre, DATE(created_at) as date FROM storyline GROUP BY created_at";
        $connexion = $this->_em->getConnection();
        $query = $connexion->prepare($sql);
        $query->execute();
        $result = $query->fetchAll();

       //dump($result); exit;

        return $result;



    }


}
