<?php

namespace NS\ScenesBundle\Repository;

/**
 * TermsOfUseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TermsOfUseRepository extends \Doctrine\ORM\EntityRepository
{
}
