<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'assetic.filter.scssphp' shared service.

include_once $this->targetDirs[3].'/vendor/kriswallsmith/assetic/src/Assetic/Filter/FilterInterface.php';
include_once $this->targetDirs[3].'/vendor/kriswallsmith/assetic/src/Assetic/Filter/DependencyExtractorInterface.php';
include_once $this->targetDirs[3].'/vendor/kriswallsmith/assetic/src/Assetic/Filter/ScssphpFilter.php';

$this->services['assetic.filter.scssphp'] = $instance = new \Assetic\Filter\ScssphpFilter();

$instance->enableCompass(false);
$instance->setImportPaths(array());
$instance->setVariables(array());
$instance->setFormatter('Leafo\\ScssPhp\\Formatter\\Compressed');

return $instance;
