<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'craue.form.flow' shared service.

include_once $this->targetDirs[3].'/vendor/craue/formflow-bundle/Form/FormFlowInterface.php';
include_once $this->targetDirs[3].'/vendor/craue/formflow-bundle/Form/FormFlow.php';

$this->services['craue.form.flow'] = $instance = new \Craue\FormFlowBundle\Form\FormFlow();

$instance->setDataManager(${($_ = isset($this->services['craue.form.flow.data_manager']) ? $this->services['craue.form.flow.data_manager'] : $this->load('getCraue_Form_Flow_DataManagerService.php')) && false ?: '_'});
$instance->setFormFactory(${($_ = isset($this->services['form.factory']) ? $this->services['form.factory'] : $this->load('getForm_FactoryService.php')) && false ?: '_'});
$instance->setRequestStack(${($_ = isset($this->services['request_stack']) ? $this->services['request_stack'] : $this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack()) && false ?: '_'});
$instance->setEventDispatcher(${($_ = isset($this->services['debug.event_dispatcher']) ? $this->services['debug.event_dispatcher'] : $this->getDebug_EventDispatcherService()) && false ?: '_'});

return $instance;
