<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'fos_comment.form_factory.comment' shared service.

include_once $this->targetDirs[3].'/vendor/friendsofsymfony/comment-bundle/FormFactory/CommentFormFactoryInterface.php';
include_once $this->targetDirs[3].'/vendor/friendsofsymfony/comment-bundle/FormFactory/CommentFormFactory.php';

return $this->services['fos_comment.form_factory.comment'] = new \FOS\CommentBundle\FormFactory\CommentFormFactory(${($_ = isset($this->services['form.factory']) ? $this->services['form.factory'] : $this->load('getForm_FactoryService.php')) && false ?: '_'}, 'FOS\\CommentBundle\\Form\\CommentType', 'fos_comment_comment');
