<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'fos_comment.listener.comment_vote_score' shared service.

include_once $this->targetDirs[3].'/vendor/friendsofsymfony/comment-bundle/EventListener/CommentVoteScoreListener.php';

return $this->services['fos_comment.listener.comment_vote_score'] = new \FOS\CommentBundle\EventListener\CommentVoteScoreListener();
