<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'fos_comment.form_factory.vote' shared service.

include_once $this->targetDirs[3].'/vendor/friendsofsymfony/comment-bundle/FormFactory/VoteFormFactoryInterface.php';
include_once $this->targetDirs[3].'/vendor/friendsofsymfony/comment-bundle/FormFactory/VoteFormFactory.php';

return $this->services['fos_comment.form_factory.vote'] = new \FOS\CommentBundle\FormFactory\VoteFormFactory(${($_ = isset($this->services['form.factory']) ? $this->services['form.factory'] : $this->load('getForm_FactoryService.php')) && false ?: '_'}, 'FOS\\CommentBundle\\Form\\VoteType', 'fos_comment_vote');
