<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'fos_comment.listener.closed_threads' shared service.

include_once $this->targetDirs[3].'/vendor/friendsofsymfony/comment-bundle/EventListener/ClosedThreadListener.php';

return $this->services['fos_comment.listener.closed_threads'] = new \FOS\CommentBundle\EventListener\ClosedThreadListener();
