<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'fos_comment.sorting_factory' shared service.

include_once $this->targetDirs[3].'/vendor/friendsofsymfony/comment-bundle/Sorting/SortingInterface.php';
include_once $this->targetDirs[3].'/vendor/friendsofsymfony/comment-bundle/Sorting/AbstractOrderSorting.php';
include_once $this->targetDirs[3].'/vendor/friendsofsymfony/comment-bundle/Sorting/DateSorting.php';
include_once $this->targetDirs[3].'/vendor/friendsofsymfony/comment-bundle/Sorting/SortingFactory.php';

return $this->services['fos_comment.sorting_factory'] = new \FOS\CommentBundle\Sorting\SortingFactory(array('date_asc' => new \FOS\CommentBundle\Sorting\DateSorting('ASC'), 'date_desc' => new \FOS\CommentBundle\Sorting\DateSorting('DESC')), 'date_desc');
