<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXtkzqxp\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXtkzqxp/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerXtkzqxp.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerXtkzqxp\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerXtkzqxp\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Xtkzqxp',
    'container.build_id' => '4e3456b3',
    'container.build_time' => 1540281651,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerXtkzqxp');
